sonar.projectKey=delcom-app-todo
sonar.projectName=delcom-app-todo

sonar.sources=src
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,src/index.mjs